name = "MAGE_ATARI"
uuid = "a6c2e983-a1f0-4880-a9cd-a0a343a4d097"
authors = ["Camilo De La Torre <camilo.de-la-torre@ut-capitole.fr> and contributors"]
version = "1.0.0-DEV"

[deps]
ArcadeLearningEnvironment = "b7f77d8d-088d-5e02-8ac0-89aab2acc977"
AtariAlgos = "faabce77-3242-5060-abab-4a4767a0df42"
SearchNetworks = "17666995-d420-48ac-8d7c-8a155fef8e5d"
UTCGP = "956831e1-0a7a-492a-ae16-058c6128a9f2"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
